import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

const gillSans = localFont({
  src: [
    {
      path: '/fonts/GillSansUltraBoNova.woff',
      weight: '1000',
      style: 'normal',
    },
    // Add other variations (italic, light, etc.) if needed
  ],
  variable: '--font-gill-sans', // This creates a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-b from-[#0a0e12] to-[#1a1f24]">
        <div className="responsive-container min-h-screen">
          {children}
        </div>
      </body>
    </html>
  )
}
